name: Momentum Rotation

on:
  schedule:
    - cron: "15 14 * * 1-5"   # Weekdays ~9:15–10:15am ET (UTC-based)
  workflow_dispatch: {}        # allow manual run

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          echo "APCA_API_KEY_ID=${{ secrets.APCA_API_KEY_ID }}" >> .env
          echo "APCA_API_SECRET_KEY=${{ secrets.APCA_API_SECRET_KEY }}" >> .env
          echo "APCA_API_BASE_URL=https://paper-api.alpaca.markets" >> .env
          # Twilio (optional) — add these secrets to enable SMS
          if [ -n "${{ secrets.TWILIO_ACCOUNT_SID }}" ]; then
            echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
            echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
            echo "TWILIO_FROM=${{ secrets.TWILIO_FROM }}" >> .env
            echo "TWILIO_TO=${{ secrets.TWILIO_TO }}" >> .env
          fi

      - name: Restore state
        uses: actions/cache@v4
        with:
          path: rotation_state.json
          key: rotation-state-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            rotation-state-

      - name: Run rotation (monthly, one-shot)
        run: |
          python momentum_rotation.py live --freq monthly --once

      - name: Save state
        if: always()
        uses: actions/cache@v4
        with:
          path: rotation_state.json
          key: rotation-state-${{ runner.os }}-${{ github.ref_name }}-${{ github.run_id }}
