name: Monthly Momentum Rotation (Alpaca Paper)

on:
  # Weekdays at ~9:15 AM New York time = 13:15 or 14:15 UTC depending on DST.
  # GitHub Actions uses UTC; adjust if you want a different moment.
  schedule:
    - cron: "15 14 * * 1-5"   # 14:15 UTC = 10:15 EDT / 9:15 EST approx pre-open
  workflow_dispatch: {}        # allow manual run from the Actions tab

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install alpaca-trade-api yfinance pandas numpy python-dateutil python-dotenv

      - name: Create .env for Alpaca Paper
        run: |
          echo "APCA_API_KEY_ID=${{ secrets.APCA_API_KEY_ID }}" >> .env
          echo "APCA_API_SECRET_KEY=${{ secrets.APCA_API_SECRET_KEY }}" >> .env
          echo "APCA_API_BASE_URL=https://paper-api.alpaca.markets" >> .env

      # Optional: restore simple month-state so we don’t rebalance twice on the same first trading day
      - name: Restore state cache
        uses: actions/cache@v4
        with:
          path: rotation_state.json
          key: rotation-state-${{ github.run_id }}
          restore-keys: |
            rotation-state-

      - name: Run monthly rotation (paper)
        run: |
          python stock_bot/momentum_rotation.py live --freq monthly --once

      # Optional: save updated state
      - name: Save state cache
        if: always()
        uses: actions/cache@v4
        with:
          path: rotation_state.json
          key: rotation-state-${{ github.run_id }}
